### PR TITLE
Ruby on Rails capstone project. I-Spend

### PR DESCRIPTION
**Pull request by TadesseDev**
# Changes introduced 😎 
> ## A mobile web application 
- I have used `Postgres` as my database. ✔
- I have used `devise` for authentication. ✔
- I have validated all user input to ensure that anyone with bad intentions cannot compromise my app. ✔
- I have used a view template engine of `.erb`. ✔
- The project is deployed and accessible online [here](https://quiet-beach-52239.herokuapp.com/)  ✔
- my database schema reflects the given [ERD](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/images/erd_diagram.png) . ✔

> [ Documentation vido](https://www.loom.com/share/79ad213e6d364d17bb1d23862164de37) 
> [ Live version](https://quiet-beach-52239.herokuapp.com/)

### CODE REVIEW

**Review by tresorsawasawa — COMMENTED** [review]
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Tadesse-Alemayehu  ,:wave: :wave: 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 🛑

You have submitted a project that doesn't correctly use GitFlow. You are supposed to create your pull request from the `dev` branch to the `main` branch and not from the feature branch `cleanup` to `dev`.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by TadesseDev** [comment]
Thanks @tresorsawasawa. I have request a code review from `dev` to `main` in one of my previous project. and it was invalidated because I was told I should have asked a review from `feature` branch to `dev`. I agree with you and I will make sure to submit a new pull request for the coming code review.

**Comment by tresorsawasawa** [comment]
Hi @Tadesse-Alemayehu

Let me ask Senior code reviewers about this issue because most of project I am getting used the same approach like you

**Comment by TadesseDev** [comment]
That would be great @tresorsawasawa. pleas let me know what the result is.

**Comment by tresorsawasawa** [comment]
Hi @Tadesse-Alemayehu 

They say that you should use **Gitflow** as I mentioned.

**Comment by TadesseDev** [comment]
Good to know @tresorsawasawa. Ill keep that in mind.

**Pull request merged**
